# Generated by Django 5.0.2 on 2024-02-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_hopperrequest_trip_delete_ride_hopperrequest_trip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='dropoff_location',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_location',
            field=models.CharField(default='', max_length=256),
        ),
    ]
