# Generated by Django 5.0.2 on 2024-02-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_hopperrequest_trip_delete_ride_hopperrequest_trip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopperrequest',
            name='hopper_status',
            field=models.IntegerField(default=0),
        ),
    ]
