# Generated by Django 5.0.2 on 2024-02-25 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_hopperrequest_hopper_status'),
        ('backend', '0003_trip_dropoff_location_trip_pickup_location'),
    ]

    operations = [
    ]
